### ISSUE TITLE
Restful

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#17]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/controller/RiotGamesController.java#L17

resource는 무엇인가요?
저는 최근 다섯게임으로 생각됩니다
자원은 복수형으로 표현한다고 말씀드렸죠?
recent-five-matches 어떤가요?

이슈는 resolve하시면 닫으시면 됩니다

**Comment by LuBly** [comment]
변경했습니다.
