### ISSUE TITLE
필드들

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#19]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L33

아래 필드들은 상수로 정의될 것이 아니라면 굳이 왜 필드로 사용하는지 모르겠네요
필요한 곳에서만 선언하고 사용하는게 좋아 보입니다

**Comment by Song-JiYeon** [comment]
done
