### ISSUE TITLE
진짜로 하는일은?

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#22]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L61

가져온 100경기 정보를 모두 topFiveGames 이름의 리스트에 추가하네요.
100경기 정보를 추가하는 리스트 이름이 왜 topFiveGames인가요?

**Comment by Song-JiYeon** [comment]
done
