### ISSUE TITLE
for문의 숫자 10

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#24]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L67

for문의 숫자 10 대신에
필드 영역에 상수를 선언해서 사용하면 코드 가독성이 좋아질 것 같은데 어떻게 생각하세요?
```private final int THE_NUMBER_OF_PLAYER = 10;```

**Comment by LuBly** [comment]
좋은것 같아요!! 적용시키겠습니다.

**Comment by LuBly** [comment]
done
