### ISSUE TITLE
필요없는 주석

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#25]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L70

필요없는 주석은 제거해주세요 어짜피 수행 되지 않는 코드이니 가독성을 해쳐요

근데 제가 리뷰해보니 break가 필요한거 같은데요.
이 코드대로라면 쓸데없이 for문이 여러번 돌 수 있네요.

**Comment by LuBly** [comment]
넵!!
