### ISSUE TITLE
동료들이 if문을 암호해독 하지 않도록

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#26]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L68

동료들이 if문을 암호해독 하지 않도록
```summonerInfo.getAccountId().equals(gameResult.getParticipantIdentities().get(j).getPlayer().getAccountId())```
부분을 좋은 이름의 private method로 빼는게 어떨까요?
`findParticipantId(SummonerInfo summonerInfo)`

**Comment by LuBly** [comment]
done
