### ISSUE TITLE
서버가 재시작 되지 않는 한

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#27]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L91

서버가 재시작 되지 않는 한,
검색된 summonerName 에 대한 Queue 추가는 발생하지 않겠군요..

**Comment by LuBly** [comment]
not using it now
