### ISSUE TITLE
60초에 한번씩 스케쥴링 해놓고

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#28]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L95

60초에 한번씩 스케쥴링 해놓고, 메소드 이름은 everyTwoSeconds 네요

**Comment by LuBly** [comment]
not using it now
