### ISSUE TITLE
주의: API 콜 횟수 제한

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#29]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/service/RiotGamesService.java#L102

주의: API 콜 횟수 제한
Queue에 들은 모든 summoner에 대해서 탐색하면서 API 콜을 하네요?
Queue에 많은 수의 summoner들이 들어있었다면 120분 100회 제한을 넘길 것 같습니다.

**Comment by LuBly** [comment]
not using it now
