### ISSUE TITLE
사용되지 않는 메소드는 제거해주세요

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#30]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/repository/RiotGamesRepository.java#L40

사용되지 않는 메소드는 제거해주세요

**Comment by LuBly** [comment]
넵!
