### ISSUE TITLE
DB에 이미 존재하는 서머너들을 이름을 모두 돌려주는 메소드 같은데

### ISSUE THREAD

**Issue by example0312** [ajou-team-3/Assignment-2-#31]
https://github.com/ajou-team-3/Assignment-2-/blob/0f752b535bdd38600fdd3a0415596f88ce00a081/src/main/java/org/ajou/realcoding/team3/secondassignment/repository/RiotGamesRepository.java#L24

DB에 이미 존재하는 서머너들을 이름을 모두 돌려주는 메소드 같은데
메소드 이름이 getAvailableSummoners 네요.
getAllRecordedSummonerNames() 어때요?

**Comment by LuBly** [comment]
지금은 사용하지 않는 메소드입니다.
